version: "3"

services:

  proxy:
    image: "traefik:2.4"
    container_name: "proxy"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
    - "--entrypoints.web.address=:80"
    - "--log.level=DEBUG"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker=true"
